config/routes.rb
Rails.application.routes.draw do
  get 'products/sort_products'
  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/contactUs'
  get 'categories/index'
  
  resources :products
  resources :categories 
  resources :reviews
  resources :cart_line_items
  resources :wishlists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :user
belongs_to :order


validates_presence_of :name,:street_address,:city,:pin_code
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name,:acc_no,:balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0

	def transaction(amount,code)
		if code==0
			if self.balance - amount < 0
				puts "Insufficient Funds"
			else
				self.balance -= amount
				self.update_attributes(balance: self.balance)
				
			end
		else
			self.balance += amount
			self.update_attributes(balance: self.balance)
		end
	end

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within: 1..10


	def save_or_update
		line_item=CartLineItem.find_by(user_id:self.user_id, product_id:self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity:line_item.quantity + self.quantity)
		end
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name

end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :order_line_items
belongs_to :user
belongs_to :address
validates_presence_of :user_id, :order_number, :order_date

# callbacks # argument (method call)
after_create :copy_cart_line_items_to_order_line_items
after_create :empty_cart_line_items
after_create :calculate_total

def copy_cart_line_items_to_order_line_items
	user = self.user
	user.cart_line_items.each do |line_item|
		order_line_item = OrderLineItem.new
		order_line_item.product_id = line_item.product_id
		order_line_item.quantity = line_item.quantity
		order_line_item.price = line_item.product.price
		order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = self.id
		order_line_item.save
	end	
end

def empty_cart_line_items
	user = self.user
	CartLineItem.delete(user.cart_line_items.pluck(:id))

end
def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end

end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :cart_line_items
	has_many :reviews
	has_many :wishlists
	has_many :order_line_items
	belongs_to :sub_category
	validates_presence_of :name,:price,:description,:category_id
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body,:rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
belongs_to :category
has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :wishlists
	has_many :orders
	has_many :addresses
	has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
validates_presence_of :name,:email,:mobile
validates_uniqueness_of :email,:mobile

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
belongs_to :product
belongs_to :user
validates_presence_of :user_id, :product_id

def save_or_update
		item=Wishlist.find_by(user_id:self.user_id, product_id:self.product_id)
		if item.nil?
			self.save
		
		end
	end

end

app/controllers/greetings.rb
class Person
	attr_accessor :first_name,:last_name
	def initialize(details)
		@first_name = details[:first_name]
	 @last_name = details[:last_name]
	end
	def details
		"Hello! #{first_name} #{last_name}"
	 
	end
end

p=Person.new({first_name:"rahul", last_name:"Patt"})
puts p.details

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
    @vendor = Vendor.new
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)
    @vendors = Vendor.all
    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
        format.js
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    @vendors = Vendor.all
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:name, :email, :mobile)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/vendors/_errors.html.erb
<div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>

app/views/vendors/_form.html.erb
<%= form_for(@vendor, remote: true) do |f| %>
  <% if @vendor.errors.any? %>
      <%= render 'errors'%>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :mobile %><br>
    <%= f.text_field :mobile %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/_table.html.erb
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Mobile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr id="tr_<%=vendor.id%>">
        <td><%= vendor.name %></td>
        <td><%= vendor.email %></td>
        <td><%= vendor.mobile %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?',remote: true } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/vendors/create.js.erb
<%if @vendor.errors.any?%>
	$('#errors').show();
	$('#errors').html("<%= escape_javascript render 'errors'%>");//errors is an id of index page
<%else%>
	$('#vendorTable').html("<%=escape_javascript render 'table'%>");
	$('#new_vendor')[0].reset();
	$('#notice').text("Vendor added successfully");
	$('#count').text("<%= @vendors.count%>");
	$('#errors').hide();//to make errors hide in index page
<%end%>

app/views/vendors/destroy.js.erb
$('#tr_<%=@vendor.id%>').fadeOut();
$('#notice').text("Vendor was deleted");
$('#count').text("<%=@vendors.count%>")

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<h1>Listing Vendors(<span id="count"></span>)</h1>

<div id="vendorTable">
  <%=render 'table'%>
</div>


<h2>Add Vendor</h2>
<span id="errors"></span>
  <%=render 'form'%>

<br>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vendor.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vendor.email %>
</p>

<p>
  <strong>Mobile:</strong>
  <%= @vendor.mobile %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>