config/routes.rb
Rails.application.routes.draw do
  get 'products/sort_products'
  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/contactUs'
  get 'categories/index'
  
  resources :products
  resources :categories 
  resources :reviews
  resources :cart_line_items
  resources :wishlists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :user
belongs_to :order


validates_presence_of :name,:street_address,:city,:pin_code
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name,:acc_no,:balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0

	def transaction(amount,code)
		if code==0
			if self.balance - amount < 0
				puts "Insufficient Funds"
			else
				self.balance -= amount
				self.update_attributes(balance: self.balance)
				
			end
		else
			self.balance += amount
			self.update_attributes(balance: self.balance)
		end
	end

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within: 1..10


	def save_or_update
		line_item=CartLineItem.find_by(user_id:self.user_id, product_id:self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity:line_item.quantity + self.quantity)
		end
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name

end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :order_line_items
belongs_to :user
belongs_to :address
validates_presence_of :user_id, :order_number, :order_date

# callbacks # argument (method call)
after_create :copy_cart_line_items_to_order_line_items
after_create :empty_cart_line_items
after_create :calculate_total

def copy_cart_line_items_to_order_line_items
	user = self.user
	user.cart_line_items.each do |line_item|
		order_line_item = OrderLineItem.new
		order_line_item.product_id = line_item.product_id
		order_line_item.quantity = line_item.quantity
		order_line_item.price = line_item.product.price
		order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = self.id
		order_line_item.save
	end	
end

def empty_cart_line_items
	user = self.user
	CartLineItem.delete(user.cart_line_items.pluck(:id))

end
def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end

end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :cart_line_items
	has_many :reviews
	has_many :wishlists
	has_many :order_line_items
	belongs_to :sub_category
	validates_presence_of :name,:price,:description,:category_id
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body,:rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
belongs_to :category
has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :wishlists
	has_many :orders
	has_many :addresses
	has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
validates_presence_of :name,:email,:mobile
validates_uniqueness_of :email,:mobile

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
belongs_to :product
belongs_to :user
validates_presence_of :user_id, :product_id

def save_or_update
		item=Wishlist.find_by(user_id:self.user_id, product_id:self.product_id)
		if item.nil?
			self.save
		
		end
	end

end

app/controllers/greetings.rb
class Person
	attr_accessor :first_name,:last_name
	def initialize(details)
		@first_name = details[:first_name]
	 @last_name = details[:last_name]
	end
	def details
		"Hello! #{first_name} #{last_name}"
	 
	end
end

p=Person.new({first_name:"rahul", last_name:"Patt"})
puts p.details

app/controllers/products_controller.rb
class ProductsController < ApplicationController

before_action :authenticate_user!, except: [:index, :show,:sort_products]
before_action :check_is_admin, except: [:index, :show,:sort_products]

def index
	
	
	@categories = Category.all
	if params[:offset]
		#binding.pry	
		if params[:ids].blank?

			@products = Product.where(price:params[:min]..params[:max]).offset(params[:offset]).limit(10)
			#binding.pry
			render json: {products:@products.map{|p| p.attributes.merge({category_name: p.category.name})}}
		else
			@products = Product.where(category_id:params[:ids].split(",")).where(price:params[:min]..params[:max]).offset(params[:offset]).limit(10)
			#binding.pry
			render json: {products:@products.map{|p| p.attributes.merge({category_name: p.category.name})}}
		end
		
		
	else

		@products = Product.limit(10)
	end
	
end


def new 
	@product = Product.new	
end

def create
	@product = Product.new(params[:product].permit(:name, :category_id, :description, :price, :code, :stock, :cod_eligible))
	if @product.save
		redirect_to products_path, notice: "successfully created the product"
	else
		render action: "new"
	end
end
def show
	@product = Product.find(params[:id])
	#@category=Category.find(@product.category_id)
	@cart_line_item = CartLineItem.new
	@review =Review.new	
	@reviews=Review.where('product_id=?',@product.id)
	
end
def edit
	@product = Product.find(params[:id])
end
def update
	@product =Product.find(params[:id])
	if @product.update_attributes(params[:product].permit(:name, :category_id, :description, :price, :code, :stock, :cod_eligible))
		redirect_to product_path(@product.id), notice: "successfully updated the product"
	else
		render action: "edit"
	end
end
def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path, notice: "successfully destroyed the product"

end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/ajax_calls_helper.rb
module AjaxCallsHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/products/_table.html.erb
<table id="productsList">
	<thead>
		<tr>
			<th>Name</th>

		</tr>
	</thead>
	<tbody>
		<tr>
			<%@products.each do |product|%>
				<td><%=product.name%></td>
		</tr>
	</tbody>
</table>

app/views/products/edit.html.erb
<h2>Edit Product</h2>
<%= form_for @product do |f| %>
	
	<%if @product.errors.any? %>
	<h3>Errors</h3>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li><%= msg  %></li>
		<%end%>
	</ul>
	<%end%>

	<label>Code:</label><br>
	<%= f.text_field :code, autofocus: true%><br>

	<label>Name:</label><br>
	<%= f.text_field :name, placeholder:"Enter the product name", autofocus: true%>
	<span id="nameError"></span><br>

	<label>Description:</label><br>
	<%= f.text_area :description  %> <br>

	<label>Price:</label><br>
	<%= f.text_field :price, min:1 %><br>

	<label>Category:</label><br>
	<%= f.collection_select :category_id , Category.all, :id, :name, prompt: "select category" %><br>

	<label>Stock:</label><br>
	<%=f.number_field :stock %><br>

	<%= check_box_tag :cod_eligible%>
	<label>Availability</label><br>


	<%= f.submit %> or <%= link_to "back", products_path %>

<% end %>

<script>
	var nameHandle = document.getElementById('product_name');
	var nameErrorHandle = document.getElementById('nameError');
	nameHandle.onblur = function(){
		if (nameHandle.value == "")
		{
			nameErrorHandle.innerHTML= "can't be blank";
		}else{
		nameErrorHandle.innerHTML="";
	}
	};

</script>

app/views/products/index.html.erb
<style>
.loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #3498db;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite;
  animation: spin 2s linear infinite;
}

@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>

<div class="row carousel-holder">

                    <div class="col-md-12">
                        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                            <ol class="carousel-indicators">
                                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                            </ol>
                            <div class="carousel-inner">
                                <div class="item active">
                                    <img class="slide-image" src="../../images/Tommy.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="../../images/Ruosh.jpg" alt="">
                                </div>
                                <div class="item">
                                    <img class="slide-image" src="../../images/Mens-Sneakers.jpg" alt="">
                                </div>
                            </div>
                            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                                <span class="glyphicon glyphicon-chevron-left"></span>
                            </a>
                            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                                <span class="glyphicon glyphicon-chevron-right"></span>
                            </a>
                        </div>
                    </div>
                    <div id="filters">
<%@categories.each do |category|%>
	<input type="checkbox" value="<%=category.id%>" id="<%=category.id%>" name ="<%=category.name%> "onchange="myFunction(<%=category.id%>)"/> <%=category.name %>
<%end%>
                </div>
                <div id="productsList"> 
               	 <div class="row">
                	<%@products.each do |product|%>
                    <div class="col-sm-6 col-md-6">
                        <div class="thumbnail">
                            <img src="http://placehold.it/320x150" alt="">
                            <div class="caption">
                                <h4 class="pull-right">₹<%=product.price%></h4>
                                <h4><%=link_to product.name, product%></h4>
                                <h6><%=product.category.name%></h6>
                                <p><%=product.description%> <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right"><%=product.reviews.count%></p>
                                <p>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                    <span class="glyphicon glyphicon-star"></span>
                                </p>
                            </div>
                        </div>
                    </div>
                	<%end%>
                </div>
          </div>

<script src="../../js/bootstrap.min.js"></script>







<div id="slider" align="right">
 Sort:
 <output id="slider1">1</output> 
 <input type="range" min="1" max="500" value="1" id="myRange1" onchange="slider1.value=value">
 <input type="range" min="500" max="1000" value="1000" id="myRange2" onchange="slider2.value=value"><output id="slider2">1000</output>
 
</div>

<%if user_signed_in? && current_user.is_admin%>
<%= link_to "AddProduct",new_product_path %>
<%end%>
<script type="text/template" id="productTemplate">
{{#products}}
	<div class="col-sm-6 col-md-6">
      <div class="thumbnail">
      	<img src="http://placehold.it/320x150" alt="">
      	 <div class="caption">
            <h4 class="pull-right">₹{{price}}</h4>
            <h4><a href="/products/{{id}}">{{name}}</a></h4>
            <h6>{{category_name}}</h6>
            <p>{{description}} <a target="_blank" href="http://www.bootsnipp.com">Bootsnipp - http://bootsnipp.com</a>.</p>
        </div>
        <div class="ratings">
            <p class="pull-right"></p>
            <p>
               <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                    <span class="glyphicon glyphicon-star"></span>
                     <span class="glyphicon glyphicon-star"></span>
                   <span class="glyphicon glyphicon-star"></span>
            </p>
        </div>
       </div>
    </div>
{{/products}}
</script>
<script>
var template = $('#productTemplate').html();
var min = document.getElementById('myRange1').value
var max = document.getElementById('myRange2').value
var offset =10;
var values=[];
var count = document.getElementById('productsCount')

$(document).ready(function(){
	$(window).on('scroll',function(){
	
		if ($(window).scrollTop() > $(document).height() - $(window).height() - 100) {
				
				getProducts(values)
			/*var xhr = new XMLHttpRequest();
			xhr.open('GET','http://localhost:3000/products?offset='+offset+'&ids='+values+'&min='+min+'&max='+max,false);
			xhr.onreadystatechange = function(){
				if (xhr.readyState === 4 && xhr.status === 200) {
					var products =JSON.parse(xhr.responseText);
					var newHtml = Mustache.to_html(template, products);

					$('#products-List').append(newHtml);
					
					offset += 10;
					
				}
				
			}
			xhr.send();*/
		}
	});
});




	
	var tableHandle = document.getElementById('myTable')
	var bodyHandle =document.getElementById('myBody')
	var sliderHandle =document.getElementById('slider')
	
	sliderHandle.addEventListener('change',function(){
		 min = document.getElementById('myRange1').value
		max = document.getElementById('myRange2').value
		//console.log(min,max)
		getProducts(values)
	},false); 
		
		
	function myFunction(ids) {
			$('#productsList').empty()
		if (document.getElementById(ids).checked) {
			if (!values.includes(ids)) 
			{
				values.push(ids);
				getProducts(values);
			}else{
				values.splice(values.indexOf(ids),1);
				getProducts(values);
				
			}
		}else{
			values.splice(values.indexOf(ids),1);
			getProducts(values);
		}
	}
	
		
	function getProducts(values){
		//console.log(values)
		$('#loader').show();
		var xhr = new XMLHttpRequest();
		offset = 0
		xhr.open('GET','http://localhost:3000/products?offset='+offset+'&ids='+values+'&min='+min+'&max='+max,false)
		
		xhr.onreadystatechange =function(){
			if (xhr.readyState === 4 && xhr.status === 200) {
				var products = JSON.parse(xhr.responseText);
				var products =JSON.parse(xhr.responseText);
					var newHtml = Mustache.to_html(template, products);

					$('#productsList').append(newHtml);
					
					offset +=10
			}
			
		}
		xhr.send();
	}

</script>

app/views/products/new.html.erb
<h2>Add Products</h2>
<%= form_for @product do |f| %>
	
	<%if @product.errors.any? %>
	<h3>Errors</h3>
	<ul>
		<% @product.errors.full_messages.each do |msg| %>
		<li><%= msg  %></li>
		<%end%>
	</ul>
	<%end%>

	<%=f.label :code%><br>
	<%= f.text_field :code, autofocus: true%><br>

	<%=f.label :name%><br>
	<%= f.text_field :name, placeholder:"Enter the product name"%>
	<span id="nameError"></span><br>

	<%=f.label :description%><br>
	<%= f.text_area :description  %> <br>

	<%=f.label :price%><br>
	<%= f.text_field :price, min:1 %><br>

	<%=f.label :category_id%><br>
	<%= f.collection_select :category_id , Category.all, :id, :name, prompt: "select category" %><br>
	<span id="productCount"></span><br>

	<%=f.label :sub_category_id%><br>
	<%= f.collection_select :sub_category_id ,[], :id, :name, prompt: "select sub category" %><br>
	

	<%=f.label :stock%><br>
	<%=f.number_field :stock %><br>

	
	<label>Available</label>
	<%= f.check_box :cod_eligible%><br>

	<%= f.submit %> or <%= link_to "back", products_path %>

<% end %>
<script type="text/javascript">
	$(document).ready(function(){
		$('#product_category_id').chosen();
	});
</script>
<script>
var categoryHandle = document.getElementById('product_category_id');
var subCategoryHandle = document.getElementById('product_sub_category_id');
categoryHandle.addEventListener('change', function(){
	subCategoryHandle.innerHTML = "";
	if (categoryHandle.value != "") {
	var xhr = new XMLHttpRequest();
	xhr.open('GET','/ajax_calls/find_sub_categories?category_id='+categoryHandle.value,true);
	xhr.onreadystatechange = function(){
		if (xhr.readyState === 4 && xhr.status === 200) {
			var subCategories = JSON.parse(xhr.responseText);
			subCategories.forEach(function(subCategory){
				
				var newElement = document.createElement('option');//<option></option>
				
				var newText = document.createTextNode(subCategory.name);//TV
				newElement.appendChild(newText);//<option>TV</option>
				newElement.setAttribute("value", subCategory.id)
				//<option value="1">TV</option>
				subCategoryHandle.appendChild(newElement);
				//console.log(subCategoryHandle)
			});

		}
	}
	xhr.send();
}else{
	document.getElementById('productCount').innerHTML=""
}
},false);


	/*var nameHandle = document.getElementById('product_name');
	var nameErrorHandle = document.getElementById('nameError');
	nameHandle.onblur = function(){
		if (nameHandle.value == "")
		{
			nameErrorHandle.innerHTML= "can't be blank";
		}else{
		nameErrorHandle.innerHTML="";
	}
	}; 
*/


</script>

app/views/products/show.html.erb
<div class="col-md-9">

                <div class="thumbnail">
                    <img class="img-responsive" src="http://placehold.it/800x300" alt="">
                    <div class="caption-full">
                        <h4 class="pull-right">₹<%=@product.price%></h4>
                        <h4><%=@product.name%>
                        </h4>
                        <p>Description:<%=@product.description%> </p>
                        <p><strong><%=link_to @product.category.name,@product.category%></strong></p>
                        <p>Stock:<%=@product.stock%></p>
                        <p>Availability:<%= @product.cod_eligible ? "Yes":"No"%></p>
                        <p>
                            <%= form_for @cart_line_item do |f|%>

                                <%=f.label :quantity%>
                                <%=f.select :quantity, (1..10).to_a%>
                                <%=f.hidden_field :product_id, value:@product.id%>

                                <%=f.submit "Add to cart", class:"btn btn-primary" %>

                            <%end%>
                        </p>
                        <p>Want to make these reviews work? Check out</p>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum</p>
                    </div>
                    <div class="ratings">
                        <p class="pull-right"><%=@product.reviews.count%> reviews</p>
                        <p>
                            <%c=@product.reviews.pluck(:rating).sum/@product.reviews.count.to_f.round%> 
                            <%c.times do%>
                                <span class="glyphicon glyphicon-star"></span>
                            <%end%>
                            <%while c < 5%>
                                <span class="glyphicon glyphicon-star-empty"></span>
                                <%c+=1%>
                            <%end%>
                            <%=@product.reviews.pluck(:rating).sum/@product.reviews.count.to_f.round%> stars
                        </p>
                    </div>
                </div>

                <div class="well">
                    <%if user_signed_in? %>
    
                        <%=render '/reviews/form'%>
        
                    <%end%>

                    
                    <hr>
                    <div id="reviewList">
                    <%@product.reviews.each do |review|%>
                    <div class="row" id="review_<%=review.id%>">
                        <div class="col-md-12">
                            <%count=0%>
                            <%review.rating.times do%>
                                <%count+=1%>
                                <span class="glyphicon glyphicon-star"></span>
                            <%end%>
                            <%while count < 5%>
                                <%count+=1%>
                                <span class="glyphicon glyphicon-star-empty"></span>
                            <%end%>

                            <%=review.user.username%>
                            <span class="pull-right">10 days ago</span>
                            <p><%=review.body%></p>
                            <%if user_signed_in? && review.user_id == current_user.id%>
                            <%=link_to "delete",review_path(review.id), method: :delete, data:{confirm:"Are you sure?" , remote: true}%>
                            <%end%>
                        </div>
                    </div>
                    <hr>
                    <%end%>
                    </div>
                </div>

            </div>























<%if user_signed_in? && current_user.is_admin%>
<%= link_to "Edit",edit_product_path(@product.id)%>
<%= link_to "destroy", product_path(@product.id) , method: :delete, data:{confirm:"Are you sure?"}%>
<%end%>