config/routes.rb
Rails.application.routes.draw do
  get 'products/sort_products'
  resources :vendors
  get 'ajax_calls/find_sub_categories'
  get 'ajax_calls/category_products'
  get 'ajax_calls/check_email_taken'
  get 'dashboard/home'

  get 'dashboard/categories'

  get 'dashboard/products'

  get 'dashboard/users'

  get 'dashboard/reviews'

  get 'dashboard/orders'

  devise_for :users
  get 'home/index'
  get 'home/about'
  get 'home/contactUs'
  get 'categories/index'
  
  resources :products
  resources :categories 
  resources :reviews
  resources :cart_line_items
  resources :wishlists
  resources :orders
  resources :addresses
  root 'products#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
belongs_to :user
belongs_to :order


validates_presence_of :name,:street_address,:city,:pin_code
end

app/models/bank_customer.rb
class BankCustomer < ActiveRecord::Base
	validates_presence_of :name,:acc_no,:balance
	validates_numericality_of :balance, greater_than_or_equal_to: 0

	def transaction(amount,code)
		if code==0
			if self.balance - amount < 0
				puts "Insufficient Funds"
			else
				self.balance -= amount
				self.update_attributes(balance: self.balance)
				
			end
		else
			self.balance += amount
			self.update_attributes(balance: self.balance)
		end
	end

end

app/models/cart_line_item.rb
class CartLineItem < ActiveRecord::Base

	belongs_to :user
	belongs_to :product

	validates_presence_of :user_id, :product_id, :quantity
	validates_numericality_of :user_id, :product_id
	validates_numericality_of :quantity, within: 1..10


	def save_or_update
		line_item=CartLineItem.find_by(user_id:self.user_id, product_id:self.product_id)
		if line_item.nil?
			self.save
		else
			line_item.update_attributes(quantity:line_item.quantity + self.quantity)
		end
	end

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
	has_many :sub_categories
	validates_presence_of :name
	validates_uniqueness_of :name

end

app/models/order.rb
class Order < ActiveRecord::Base
has_many :order_line_items
belongs_to :user
belongs_to :address
validates_presence_of :user_id, :order_number, :order_date

# callbacks # argument (method call)
after_create :copy_cart_line_items_to_order_line_items
after_create :empty_cart_line_items
after_create :calculate_total

def copy_cart_line_items_to_order_line_items
	user = self.user
	user.cart_line_items.each do |line_item|
		order_line_item = OrderLineItem.new
		order_line_item.product_id = line_item.product_id
		order_line_item.quantity = line_item.quantity
		order_line_item.price = line_item.product.price
		order_line_item.total = line_item.quantity * line_item.product.price
		order_line_item.order_id = self.id
		order_line_item.save
	end	
end

def empty_cart_line_items
	user = self.user
	CartLineItem.delete(user.cart_line_items.pluck(:id))

end
def calculate_total
		self.update_attributes(total: self.order_line_items.sum(:total))
	end

end

app/models/order_line_item.rb
class OrderLineItem < ActiveRecord::Base
belongs_to :order
belongs_to :product
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
	has_many :cart_line_items
	has_many :reviews
	has_many :wishlists
	has_many :order_line_items
	belongs_to :sub_category
	validates_presence_of :name,:price,:description,:category_id
	validates_numericality_of :price, :category_id, greater_than_or_equal_to: 1
	
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :product
	belongs_to :user

	validates_presence_of :body,:rating
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
belongs_to :category
has_many :products
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :cart_line_items
	has_many :wishlists
	has_many :orders
	has_many :addresses
	has_many :reviews

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
validates_presence_of :name,:email,:mobile
validates_uniqueness_of :email,:mobile

end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
belongs_to :product
belongs_to :user
validates_presence_of :user_id, :product_id

def save_or_update
		item=Wishlist.find_by(user_id:self.user_id, product_id:self.product_id)
		if item.nil?
			self.save
		
		end
	end

end

app/controllers/greetings.rb
class Person
	attr_accessor :first_name,:last_name
	def initialize(details)
		@first_name = details[:first_name]
	 @last_name = details[:last_name]
	end
	def details
		"Hello! #{first_name} #{last_name}"
	 
	end
end

p=Person.new({first_name:"rahul", last_name:"Patt"})
puts p.details

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ecommerce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <script src="../jquery-ui.js"></script>
  <link rel="stylesheet" href="../jquery-ui.css">
    <script src="../chosen.jquery.js"></script>
  <link rel="stylesheet" href="../chosen.css">
  <!-- Bootstrap Core CSS -->
    <link href="../css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="../css/shop-homepage.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js"></script>

   <link rel="stylesheet" href="//cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css">
    <script type="text/javascript" src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>

  <%= csrf_meta_tags %>
</head>
<body>


	<div class="container">
	<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/products">E-Commerce</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    
                        <%if user_signed_in?%>
                        <li><%=link_to current_user.username.capitalize%></li>
                        <li><%=link_to "cart",cart_line_items_path%></li> 
                        <li><%=link_to "orders", orders_path%> </li>
                        <li><%=link_to "wishlist", wishlists_path%> </li>
                        <li><%=link_to "Account setting",edit_user_registration_path%> </li>
                        <li><%=link_to "Logout",destroy_user_session_path, method: :delete%></li>
                        <%else%>
                        <li><%=link_to "login",new_user_session_path%></li>
                        <li><%=link_to "Register",new_user_registration_path%></li>
                        
                        <%end%>
                                        
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>
		<!-- Page Content -->
    <div class="container">

        <div class="row">

            <div class="col-md-3">
                <p class="lead">Categories</p>
                <div class="list-group">
                <%Category.all.each do |category|%>
                	<%=link_to category.name, category, class:"list-group-item"%>
                <%end%>
                    
                </div>
            </div>

            <div class="col-md-9">
            	<p class="notice"><%= notice %></p>
				<p class="alert"><%= alert %></p>
				<%= yield %>

               

            </div>

        </div>

    </div>




		

	</div>

</body>
</html>

app/views/notification/order_confirmation.html.erb
<p>Hi <%= @order.user.username %>, <br/>
 Your order has been confirmed </p>

            <h4><%= @order.order_number %>  
                <%= @order.order_date %> 
                <%= @order.total %> </h4>
    
    <ul>
        <% @order.order_line_items.each do |line_item| %>
            <li><%= line_item.product.name %> INR <%= line_item.price %> <%= line_item.quantity %> <%= line_item.total %></li>
        <% end %>
    </ul>

<b> Thank you for placing an order with us</b>

app/views/notification/order_confirmation.text.erb
Notification#order_confirmation

 find me in app/views/notification/order_confirmation.text.erb

app/views/notification/review_greetings.html.erb
<p>Hi <%=@review.user.username%><br>
Thank you for reviewing the product <%=@review.product.name%><br>
Review:<%=@review.body%><br>
Rating:<%=@review.rating%>
	
</p>